package com.nabd.phone;

import android.Manifest;
import android.app.*;
import android.app.role.RoleManager;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.CallLog;
import android.provider.ContactsContract;
import android.telecom.TelecomManager;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    final int PERMS=42; LinearLayout root, content; boolean dark=true; int mint=Color.rgb(112,225,193); String[] tabs={"السجل","جهات الاتصال","لوحة التحكم"};
    int bg(){return dark?Color.rgb(11,18,32):Color.rgb(246,248,251);} int card(){return dark?Color.rgb(20,31,51):Color.WHITE;} int fg(){return dark?Color.rgb(247,250,252):Color.rgb(16,28,45);} int muted(){return dark?Color.rgb(158,174,194):Color.rgb(101,116,136);}
    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(11,18,32)); build(); requestPermissionsIfNeeded();}
    TextView text(String s,float size,int color){TextView t=new TextView(this); t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setTypeface(Typeface.create("sans",Typeface.NORMAL));t.setPadding(16,8,16,8);return t;}
    GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
    Button button(String label){Button b=new Button(this);b.setText(label);b.setTextColor(dark?Color.rgb(11,18,32):Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(bg(mint,22));b.setPadding(18,4,18,4);return b;}
    void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg());root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); setContentView(root); header(); content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(18,8,18,10);root.addView(content,new LinearLayout.LayoutParams(-1,0,1)); nav(); showLog();}
    void header(){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(20,12,20,8);h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); TextView brand=text("نَبْض\nمركز اتصالاتك",22,fg());brand.setTypeface(Typeface.DEFAULT_BOLD);h.addView(brand,new LinearLayout.LayoutParams(0,72,1)); Button theme=button(dark?"☀  نهاري":"☾  ليلي");theme.setOnClickListener(v->{dark=!dark;build();});h.addView(theme,new LinearLayout.LayoutParams(-2,52));root.addView(h);}
    void nav(){LinearLayout n=new LinearLayout(this);n.setPadding(12,8,12,14);n.setGravity(Gravity.CENTER);n.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); for(String tab:tabs){Button b=button(tab);b.setBackground(bg(tab.equals(tabs[0])?mint:card(),18)); b.setTextColor(tab.equals(tabs[0])?Color.rgb(11,18,32):fg());b.setOnClickListener(v->{if(tab.equals("السجل"))showLog();else if(tab.equals("جهات الاتصال"))showContacts();else showSettings();});n.addView(b,new LinearLayout.LayoutParams(0,52,1));} root.addView(n);}
    TextView title(String s,String sub){TextView t=text(s+"\n"+sub,26,fg());t.setTypeface(Typeface.DEFAULT_BOLD);t.setPadding(4,16,4,18);return t;}
    void clear(){content.removeAllViews();}
    void showLog(){clear();content.addView(title("سجل الاتصالات","بيانات الجهاز الحقيقية • بدون تسجيل صوت المكالمات")); LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER_VERTICAL);actions.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);Button refresh=button("تحديث");refresh.setOnClickListener(v->showLog());actions.addView(refresh);Button role=button("تطبيق الهاتف الافتراضي");role.setOnClickListener(v->requestDialerRole());actions.addView(role);content.addView(actions); addSpace(); Cursor c=null; try{if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_CALL_LOG)!=PackageManager.PERMISSION_GRANTED){empty("امنح صلاحية سجل المكالمات لعرض البيانات الحقيقية");return;} c=getContentResolver().query(CallLog.Calls.CONTENT_URI,null,null,null,CallLog.Calls.DATE+" DESC");int count=0;while(c!=null&&c.moveToNext()&&count<80){String num=c.getString(c.getColumnIndexOrThrow(CallLog.Calls.NUMBER));int type=c.getInt(c.getColumnIndexOrThrow(CallLog.Calls.TYPE));long date=c.getLong(c.getColumnIndexOrThrow(CallLog.Calls.DATE));long dur=c.getLong(c.getColumnIndexOrThrow(CallLog.Calls.DURATION));String label=type==CallLog.Calls.INCOMING_TYPE?"واردة":type==CallLog.Calls.OUTGOING_TYPE?"صادرة":type==CallLog.Calls.MISSED_TYPE?"فائتة":type==CallLog.Calls.REJECTED_TYPE?"مرفوضة":"غير محددة"; addCall(num,label,date,dur);count++;}if(count==0)empty("لا توجد مكالمات في سجل الجهاز");}catch(Exception e){empty("تعذر قراءة سجل المكالمات: "+e.getMessage());}finally{if(c!=null)c.close();}}
    void addCall(String num,String label,long date,long dur){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(12,12,12,12);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.setBackground(bg(card(),26));TextView icon=text(label.equals("فائتة")?"↙":label.equals("واردة")?"↘":"↗",28,label.equals("فائتة")?Color.rgb(255,111,125):mint);row.addView(icon,new LinearLayout.LayoutParams(54,70));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setGravity(Gravity.RIGHT);info.addView(text(num,18,fg()));String d=new SimpleDateFormat("yyyy/MM/dd  HH:mm",Locale.getDefault()).format(new Date(date));info.addView(text(label+"  •  "+d+"  •  "+dur+"ث",12,muted()));row.addView(info,new LinearLayout.LayoutParams(0,70,1));Button call=button("اتصال");call.setOnClickListener(v->dial(num));row.addView(call,new LinearLayout.LayoutParams(-2,52));content.addView(row,new LinearLayout.LayoutParams(-1,86));addSpace();}
    void showContacts(){clear();content.addView(title("جهات الاتصال","الأسماء والأرقام الموجودة فعليًا على الهاتف"));EditText search=new EditText(this);search.setHint("ابحث بالاسم أو الرقم");search.setTextColor(fg());search.setHintTextColor(muted());search.setBackground(bg(card(),22));content.addView(search,new LinearLayout.LayoutParams(-1,58));addSpace();loadContacts("");search.setOnEditorActionListener((v,a,e)->{loadContacts(search.getText().toString());return true;});}
    void loadContacts(String q){for(int i=content.getChildCount()-1;i>1;i--)content.removeViewAt(i);Cursor c=null;try{if(checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED){empty("امنح صلاحية جهات الاتصال لعرض البيانات الحقيقية");return;}String sel=ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME+" LIKE ? OR "+ContactsContract.CommonDataKinds.Phone.NUMBER+" LIKE ?";String x="%"+q+"%";c=getContentResolver().query(ContactsContract.CommonDataKinds.Phone.CONTENT_URI,new String[]{ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME,ContactsContract.CommonDataKinds.Phone.NUMBER},q.isEmpty()?null:sel,q.isEmpty()?null:new String[]{x,x},ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME+" ASC");int n=0;while(c!=null&&c.moveToNext()&&n<150){addContact(c.getString(0),c.getString(1));n++;}if(n==0)empty("لا توجد جهات اتصال مطابقة");}finally{if(c!=null)c.close();}}
    void addContact(String name,String num){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(12,8,12,8);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);TextView avatar=text(name==null||name.isEmpty()?"؟":name.substring(0,1),24,Color.rgb(11,18,32));avatar.setGravity(Gravity.CENTER);avatar.setBackground(bg(mint,60));row.addView(avatar,new LinearLayout.LayoutParams(54,54));LinearLayout inf=new LinearLayout(this);inf.setOrientation(LinearLayout.VERTICAL);inf.addView(text(name==null?"بدون اسم":name,17,fg()));inf.addView(text(num,13,muted()));row.addView(inf,new LinearLayout.LayoutParams(0,70,1));Button b=button("اتصال");b.setOnClickListener(v->dial(num));row.addView(b,new LinearLayout.LayoutParams(-2,52));content.addView(row,new LinearLayout.LayoutParams(-1,78));}
    void showSettings(){clear();content.addView(title("لوحة التحكم","إعدادات نبض وصلاحيات النظام"));panel("الوضع الحالي",dark?"ليلي • ألوان كحلية ونعناعية":"نهاري • ألوان فاتحة",button(dark?"تفعيل النهاري":"تفعيل الليلي"));panel("بيانات حقيقية","المكالمات وجهات الاتصال تُقرأ من جهازك بعد موافقتك. لا نستخدم أرقامًا تجريبية ولا نسجل الصوت.",button("إدارة الصلاحيات"));panel("واتساب","يفتح التطبيق الرسمي على الرقم عند توفره، ولا ندّعي حالة الحساب بدون API مصادق عليه.",button("فتح إعدادات التطبيقات"));Button role=button("اختيار نبض كتطبيق الهاتف الافتراضي");role.setOnClickListener(v->requestDialerRole());content.addView(role,new LinearLayout.LayoutParams(-1,58));}
    void panel(String h,String s,Button b){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(18,16,18,16);p.setBackground(bg(card(),28));p.addView(text(h,18,fg()));p.addView(text(s,13,muted()));b.setOnClickListener(v->requestPermissionsIfNeeded());p.addView(b,new LinearLayout.LayoutParams(-2,52));content.addView(p,new LinearLayout.LayoutParams(-1,-2));addSpace();}
    void empty(String s){TextView e=text("\n"+s+"\n",16,muted());e.setGravity(Gravity.CENTER);content.addView(e,new LinearLayout.LayoutParams(-1,140));}
    void addSpace(){Space s=new Space(this);content.addView(s,new LinearLayout.LayoutParams(1,10));}
    void dial(String n){try{startActivity(new Intent(Intent.ACTION_CALL,Uri.parse("tel:"+Uri.encode(n))));}catch(Exception e){startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+Uri.encode(n))));}}
    void requestPermissionsIfNeeded(){if(Build.VERSION.SDK_INT>=23)requestPermissions(new String[]{Manifest.permission.READ_CONTACTS,Manifest.permission.READ_CALL_LOG,Manifest.permission.CALL_PHONE,Manifest.permission.READ_PHONE_STATE},PERMS);}
    void requestDialerRole(){if(Build.VERSION.SDK_INT>=29){RoleManager rm=getSystemService(RoleManager.class);if(rm.isRoleAvailable(RoleManager.ROLE_DIALER)&&!rm.isRoleHeld(RoleManager.ROLE_DIALER))startActivityForResult(rm.createRequestRoleIntent(RoleManager.ROLE_DIALER),77);else Toast.makeText(this,"نبض هو تطبيق الهاتف الافتراضي بالفعل",Toast.LENGTH_LONG).show();}else Toast.makeText(this,"يتطلب هذا الإصدار دعم تطبيق الهاتف الافتراضي",Toast.LENGTH_LONG).show();}
}
